/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    noticias: Noticia;
    galeria: Galeria;
    eventos: Evento;
    'categorias-noticias': CategoriasNoticia;
    'categorias-eventos': CategoriasEvento;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    noticias: NoticiasSelect<false> | NoticiasSelect<true>;
    galeria: GaleriaSelect<false> | GaleriaSelect<true>;
    eventos: EventosSelect<false> | EventosSelect<true>;
    'categorias-noticias': CategoriasNoticiasSelect<false> | CategoriasNoticiasSelect<true>;
    'categorias-eventos': CategoriasEventosSelect<false> | CategoriasEventosSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Artigos e notícias do site. Salve como rascunho e publique quando estiver pronto.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias".
 */
export interface Noticia {
  id: number;
  title: string;
  /**
   * Parte final da URL, ex.: primeira-feira-das-nacoes-apae-barueri
   */
  slug: string;
  /**
   * Escolha uma categoria da lista (ou crie uma nova).
   */
  category: number | CategoriasNoticia;
  /**
   * Texto curto, ex.: "Jun 2026"
   */
  date: string;
  publishedTime?: string | null;
  excerpt: string;
  image?: (number | null) | Media;
  /**
   * Descreve a capa para leitores de tela. Usa o título se vazio.
   */
  imageAlt?: string | null;
  /**
   * Ex.: "Imagem ilustrativa".
   */
  imageCaption?: string | null;
  /**
   * Preview ao compartilhar no WhatsApp/redes. Usa a capa se vazio.
   */
  ogImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Opcional. Vincula um álbum da Galeria ao final do artigo.
   */
  galleryAlbum?: (number | null) | Galeria;
  /**
   * Ex.: "Veja as fotos do evento".
   */
  galleryHeading?: string | null;
  /**
   * Usa o título se vazio
   */
  seoTitle?: string | null;
  /**
   * Usa o resumo se vazio
   */
  metaDescription?: string | null;
  /**
   * Ex.: "4 min de leitura"
   */
  readTime?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Categorias que aparecem ao classificar uma notícia. Evite criar muitas parecidas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias-noticias".
 */
export interface CategoriasNoticia {
  id: number;
  /**
   * Ex.: Institucional, Eventos, Voluntariado.
   */
  nome: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descreva a imagem para leitores de tela e SEO.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Álbuns de fotos da página Galeria. A capa (ou a 1ª foto) aparece no cartão do álbum.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galeria".
 */
export interface Galeria {
  id: number;
  /**
   * Ex.: 30 Anos da APAE Barueri 2026.
   */
  title: string;
  /**
   * Usado no link da galeria. Sem espaços nem acentos. Ex.: aniversario-30-anos-2026.
   */
  slug: string;
  /**
   * Imagem do cartão do álbum. Se vazia, usa a primeira foto.
   */
  cover?: (number | null) | Media;
  /**
   * Arraste para reordenar. A ordem aqui é a ordem que aparece no site.
   */
  photos?:
    | {
        image: number | Media;
        /**
         * Descrição da foto (acessibilidade e legenda).
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Eventos da agenda. Inclui eventos com data marcada e eventos recorrentes (sem data fixa).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventos".
 */
export interface Evento {
  id: number;
  titulo: string;
  tipoData: 'dia' | 'mes' | 'recorrente';
  /**
   * Para "mês inteiro", escolha qualquer dia do mês (o dia será ignorado).
   */
  data?: string | null;
  /**
   * Ex.: "Segunda a quinta-feira", "Mensal".
   */
  recorrencia?: string | null;
  /**
   * Sobrescreve a data exibida. Ex.: "8 a 12 Jun 2026" para eventos de vários dias.
   */
  dataExibicao?: string | null;
  /**
   * Define a cor do evento na agenda.
   */
  categoria: number | CategoriasEvento;
  /**
   * Ex.: "Sede APAE Barueri · 9h às 12h".
   */
  local: string;
  descricao: string;
  /**
   * Eventos em destaque aparecem com mais ênfase na agenda.
   */
  destaque?: boolean | null;
  /**
   * Sem espaços nem acentos. Ex.: bazar-inverno-2026.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Categorias dos eventos. A cor define como o evento aparece destacado na agenda.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias-eventos".
 */
export interface CategoriasEvento {
  id: number;
  /**
   * Ex.: Celebração, Captação, Mobilização.
   */
  nome: string;
  /**
   * Ex.: #FFCC00 (amarelo), #005DAA (azul).
   */
  cor?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pessoas com acesso ao painel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'noticias';
        value: number | Noticia;
      } | null)
    | ({
        relationTo: 'galeria';
        value: number | Galeria;
      } | null)
    | ({
        relationTo: 'eventos';
        value: number | Evento;
      } | null)
    | ({
        relationTo: 'categorias-noticias';
        value: number | CategoriasNoticia;
      } | null)
    | ({
        relationTo: 'categorias-eventos';
        value: number | CategoriasEvento;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias_select".
 */
export interface NoticiasSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  date?: T;
  publishedTime?: T;
  excerpt?: T;
  image?: T;
  imageAlt?: T;
  imageCaption?: T;
  ogImage?: T;
  body?: T;
  galleryAlbum?: T;
  galleryHeading?: T;
  seoTitle?: T;
  metaDescription?: T;
  readTime?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galeria_select".
 */
export interface GaleriaSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  cover?: T;
  photos?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventos_select".
 */
export interface EventosSelect<T extends boolean = true> {
  titulo?: T;
  tipoData?: T;
  data?: T;
  recorrencia?: T;
  dataExibicao?: T;
  categoria?: T;
  local?: T;
  descricao?: T;
  destaque?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias-noticias_select".
 */
export interface CategoriasNoticiasSelect<T extends boolean = true> {
  nome?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias-eventos_select".
 */
export interface CategoriasEventosSelect<T extends boolean = true> {
  nome?: T;
  cor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}